config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "products#index"
  resources :products
  get '/cart', to: 'carts#show'
  post '/cart', to: 'carts#update'
  delete '/cart', to: 'carts#destroy'

  # resources :carts, except: [:index, :new, :show]
  # resources :charges
  post 'charges', to: "charges#create"
  get 'thanks', to: "charges#thanks"

  # auth
  get '/login',                  to: 'sessions#new'
  post '/login',                 to: 'sessions#create'
  get '/logout',                 to: 'sessions#destroy'
  get '/signup',                 to: 'users#new'
  get '/confirm/:token',         to: 'users#confirm'
  get '/forgot',                 to: 'users#forgot', as: 'forgot'
  post '/forgot_password',       to: 'users#forgot_password', as: 'forgot_password'
  get '/reset/:token',           to: 'users#reset', as: 'reset'
  patch '/reset_password/:token', to: 'users#reset_password', as: 'reset_password'
  resources :users
  resources :dealers

  mount Sidekiq::Web => "/sidekiq"
end

app/views/partials/_comment.haml
.comment{"data-comment-id": c.id, "data-endpoint": endpoint}
  .body
    %b
      = c.user.username
    = c.body

  .subtitle
    .item.mr-2
      %a{href: "#", "data-reply": ""}
        reply
    .item.mr-2
      %a{href: "#", "data-cancel": ""}
        cancel
    .item.mr-2
      = time_ago_in_words(c.created_at)


  .reply-form{"id": "comment-#{c.id}"}

  - if c.children
    .parent-comment
      - c.children.each do |child|
        .ml-4
          = render partial: "partials/comment", locals: {c: child, endpoint: "/ideas/#{@idea.id}/comment"}

app/views/partials/_idea.haml
.row.project
  .col-lg-2
    - if p.image.attachment
      .idea-image{style: "background-image: url('#{url_for(p.image)}')"}
    - else
      .idea-image{style: "background-image: url(#{random_image})"}
  .col-lg-8
    %h6.title
      = link_to p.title, idea_path(p.id)
    .subtitle
      .item.mr-2
        = link_to p.user.username, user_path(p.user.id)
      .item.mr-2
        = time_ago_in_words(p.created_at)
        ago
      .item.mr-2
        = p.comments.count
        comments
    .description
      = truncate_html(p.description.html_safe, length: 200)
  .col-lg-2
    // break to a partial
    - if current_user
      %button.vote.pull-right{data: {vote: "", url: vote_idea_path(p.id), id: p.id, count: p.votes.count, toggled: "#{user_voted?(p.id)}"}}
        = fa_icon "arrow-up"
        %span.count
          = p.votes.count
    - else
      %a.vote.pull-right{href: "/login"}
        = fa_icon "arrow-up"
        %span.count
          = p.votes.count

app/views/partials/_idea_form.haml
= form_for @idea do |p|
  -# once we figure out storage, we can re-enable this
  .custom-file
    -# %label{class: "custom-file-label", for:"customFile"}
    -#   Choose file
    = p.file_field :image, direct_upload: true
    %p
      %small
        (5MB max)
  .form-group
    = p.label :title
    = p.text_field :title, class: "form-control", required: true
  .form-group
    = p.label :description
    = p.hidden_field :description, required: true, id: "x"
    %trix-editor{input: "x", class: "form-control"}
  .form-group
    = p.fields_for :tags, @idea.tags do |t|
      %label
        Tags
        .tag-container
          #idea_tags
  .form-group
    = p.submit

app/views/partials/_idea_list.haml
.col-9
  .projects
    .header
      %h4
        = @header
    - if @ideas
      - @ideas.each do |p|
        = render partial: "partials/idea", locals: { p: p }

app/views/partials/_login_form.haml
= form_for @user, url: login_path do |p|
  .form-group
    %label
      Email or Username
    = p.text_field :email, class: "form-control"
  .form-group
    = p.label :password
    = p.password_field :password, class: "form-control"
  .form-group
    = p.submit "Log In", class: "btn btn-primary"

app/views/partials/_nav.haml
%nav.navbar.navbar-light.navbar-expand-lg
  .container
    = link_to image_tag("logo.png"), '/', class: "navbar-brand"
    .navbar-collapse
      - if current_user
        %ul.navbar-nav.ml-auto
          %li.nav-item
            = link_to "New Idea", new_idea_path, class: "nav-link"
          %li.nav-item
            = link_to "My Ideas", me_ideas_path, class: "nav-link"
          %li.nav-item
            = link_to "Upvoted", voted_ideas_path, class: "nav-link"
          -# %li.nav-item
          -#   = link_to "Messages", messages_path, class: "nav-link border-right"
          %li.nav-item
            = link_to "Users", users_path, class: "nav-link border-right"
          %li.nav-item
            = link_to current_user.email, edit_user_path(current_user.id), class: "nav-link"
          %li.nav-item
            = link_to "Log Out", logout_path, class: "nav-link"
      - else
        %ul.navbar-nav.ml-auto
          %li.nav-item
            = link_to "Sign Up", signup_path, class: "nav-link"
          %li.nav-item
            = link_to "Log In", login_path, class: "nav-link"
          %li.nav-item
            = link_to "Explore", explore_path, class: "nav-link"

app/views/partials/_project_list.haml
.col-9
  .projects
    .header
      %h4
        = @header
    - if @ideas
      - @ideas.each do |p|
        = render partial: "partials/idea", locals: { p: p }

app/views/partials/_sidebar.haml
.col-3
  .sidebar
    %h4
      Brands
    %ul.sidebar
      - Brand.all.each do |brand|
        %li.sidebar-item
          %img.brand-logo{:src => "https://source.unsplash.com/100x100/?music"}/
          = brand.name

app/views/partials/_sign_up_form.haml
= form_for @user, url: {action: "create"} do |p|
  .form-group
    = p.label :username
    = p.text_field :username, required: true, class: "form-control"
  .form-group
    = p.label :email
    = p.text_field :email, required: true, class: "form-control"
  .form-group
    = p.label :password
    = p.password_field :password, required: true, class: "form-control"
  .form-group
    = p.label :password_confirmation
    = p.password_field :password_confirmation, required: true, class: "form-control"
  .form-group
    = p.label "Seller?"
    = p.check_box :seller, class: "form-control"
  .form-group
    = p.submit "Sign Up", class: "btn btn-primary"

app/views/partials/_subscribe_form.haml
.row.subscribe-form
  = form_for Subscriber.new, action: "create", html: {class: "form-inline mx-auto"} do |s|
    %h6{style: "display: inline;"}
      Get a feed of new ideas every week.
    .form-group.mb-2
      = s.text_field :email, placeholder: "Email"
    .form-group.mb-2
      = s.submit value: "Send!"

app/views/partials/_suggestion_widget.haml
= link_to "Feedback", new_suggestion_path, class: "suggestion-widget"

app/views/partials/suggestion_widget.haml
= link_to "Feedback", new_suggestion_path, class: "suggestion-widget"