config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "products#index"
  resources :products
  get '/cart', to: 'carts#show'
  post '/cart', to: 'carts#update'
  delete '/cart', to: 'carts#destroy'

  # resources :carts, except: [:index, :new, :show]
  # resources :charges
  post 'charges', to: "charges#create"
  get 'thanks', to: "charges#thanks"

  # auth
  get '/login',                  to: 'sessions#new'
  post '/login',                 to: 'sessions#create'
  get '/logout',                 to: 'sessions#destroy'
  get '/signup',                 to: 'users#new'
  get '/confirm/:token',         to: 'users#confirm'
  get '/forgot',                 to: 'users#forgot', as: 'forgot'
  post '/forgot_password',       to: 'users#forgot_password', as: 'forgot_password'
  get '/reset/:token',           to: 'users#reset', as: 'reset'
  patch '/reset_password/:token', to: 'users#reset_password', as: 'reset_password'
  resources :users
  resources :dealers

  mount Sidekiq::Web => "/sidekiq"
end

app/models/user.rb
class User < ApplicationRecord
  include Rails.application.routes.url_helpers

  has_secure_password
  has_many :carts
  has_many :orders

  before_create :generate_confirm_token
  before_create :generate_reset_token
  before_create :downcase_email

  validates_uniqueness_of :email

  def generate_confirm_token
    self.confirmation_token = SecureRandom.uuid
  end

  def confirmation_link
    "#{ENV['APP_URL']}/confirm/#{self.confirmation_token}"
  end

  def send_confirmation_email
    UserConfirmationMailer.confirmation_email(self).deliver_later
  end

  def generate_reset_token
    self.reset_token = SecureRandom.uuid
  end

  def reset_link
    "#{ENV['APP_URL']}/reset/#{self.reset_token}"
  end

  def send_reset_email
    UserResetMailer.reset_email(self).deliver_later
  end

  def downcase_email
    self.email = email.downcase
  end

  def current_cart
    carts.current.last
  end

  def paid_cart
    carts.paid.last
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @header = @user.username if @user
    # @ideas = @user.ideas
  end

  def new
    @user = User.new
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_user_path(current_user)
      flash[:info] = "Profile Updated"
    end
  end

  def create
    @user = User.find_by(email: user_params[:email])
    @new_user = User.new(user_params)
    if @user
      redirect_to login_path
      flash[:info] = "An account already exists with this email. Please login"
    elsif !@user && @new_user.save
      if user_params[:seller]
        redirect_to new_dealer_path and return
      end
      @new_user.send_confirmation_email
      redirect_to login_path
      flash[:info] = "Click the link sent in the confirmation email to login."
    else
      redirect_to signup_path
      flash[:danger] = "#{@new_user.errors.full_messages}"
    end
  end

  def edit
    @user = User.find(params[:id])
    if !current_user
      redirect_to login_path
      flash[:danger] = "Login before trying that"
    elsif current_user != @user
      redirect_to edit_user_path(current_user)
      flash[:danger] = "Not permitted to view others profiles, dude."
    end
  end

  def confirm
    @user = User.find_by(confirmation_token: params[:token])
    if @user.update_attributes(confirmed_at: DateTime.now)
      redirect_to login_path
      flash[:info] = "Confirmed! Log In."
    else
      redirect_to login_path
      flash[:danger] = "There was an error with your credentials"
    end
  end

  def forgot
  end

  def forgot_password
    @user = User.find_by(email: params[:email])
    if @user.send_reset_email
      redirect_to forgot_path
      flash[:info] = "Follow the link in the email to reset."
    else
      redirect_to forgot_path
      flash[:error] = "Error sending reset email."
    end
  end

  def reset
    # get
    @user= User.find_by(reset_token: params[:token])
  end

  def reset_password
    #post/patch
    @user = User.find_by(reset_token: params[:token])
    u = @user
    u.password = params[:user][:password]
    u.password_confirmation = params[:user][:password]
    if u.save
      flash[:info] = "Password successfully reset."
      redirect_to login_path
    else
      flash[:danger] = "There was en error resetting your password."
      redirect_to reset_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :seller, :username)
  end
end

app/views/users/edit.haml
.row
  .col-6.mx-auto.centered-form
    %h2
      #{@user.email}'s profile

    = form_for @user do |p|
      .form-group
        = p.label :username
        = p.text_field :username
      .form-group
        = p.label :years_experience
        = p.number_field :years_experience
      .form-group
        = p.label :website_url
        = p.text_field :website_url
      .form-group
        = p.label :github_url
        = p.text_field :github_url
      = p.submit

app/views/users/forgot.haml
.col-6.mx-auto.centered-form
  %p
    If we find the email you enter, we will send you a reset email.🤘
  = form_tag forgot_password_path do |p|
    .form-group
      %label{for: "email"}
        Email
      %input{type: "text", name: "email"}

    .form-group
      %input{type: 'submit', class: "btn btn-primary", value: "Reset"}

app/views/users/index.haml
.container
  .row
    = render partial: "partials/sidebar"
    .col-9
      .row
        .col-12
          %h4
            Users
      - if @users
        - @users.each do |u|
          .row.user
            .col-lg-2
              .idea-letter{style: "border: 1px solid #{random_color}"}
                = link_to u.email[0], user_path(u.id)
            .col-lg-10
              %h6.title
                = link_to u.username, user_path(u.id)
              %p
                = u.ideas.count
                Ideas

app/views/users/new.haml
.row
  .col-6.mx-auto.centered-form

    %h3
      Sign Up
    = render partial: "partials/sign_up_form", locals: {user: @user}

app/views/users/reset.haml
.col-6.mx-auto.centered-form
  = form_for @user, url: reset_password_path(@user.reset_token) do |p|
    .form-group
      = p.label :password
      = p.password_field :password
    .form-group
      = p.label :password_confirmation
      = p.password_field :password_confirmation
    .form-group
      = p.submit

app/views/users/show.haml
.row
  -# = render "partials/sidebar"
  .col-12
    .item-list
      .item.row
        .col-2
          %img.item-image{:src => "https://source.unsplash.com/100x100/?nature"}/
        .col-10
          .item-title
            = @item.name
          .price
            = @item.price
          .stats
            = @item.amount
            available