config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "products#index"
  resources :products
  get '/cart', to: 'carts#show'
  post '/cart', to: 'carts#update'
  delete '/cart', to: 'carts#destroy'

  # resources :carts, except: [:index, :new, :show]
  # resources :charges
  post 'charges', to: "charges#create"
  get 'thanks', to: "charges#thanks"

  # auth
  get '/login',                  to: 'sessions#new'
  post '/login',                 to: 'sessions#create'
  get '/logout',                 to: 'sessions#destroy'
  get '/signup',                 to: 'users#new'
  get '/confirm/:token',         to: 'users#confirm'
  get '/forgot',                 to: 'users#forgot', as: 'forgot'
  post '/forgot_password',       to: 'users#forgot_password', as: 'forgot_password'
  get '/reset/:token',           to: 'users#reset', as: 'reset'
  patch '/reset_password/:token', to: 'users#reset_password', as: 'reset_password'
  resources :users
  resources :dealers

  mount Sidekiq::Web => "/sidekiq"
end

app/models/product.rb
class Product < ApplicationRecord
    # composed_of :price,
    #   :class_name => 'Money',
    #   :mapping => %w(price cents),
    #   :converter => Proc.new { |value| Money.new(value) }
    validates_presence_of :price
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @header = "All Ideas"
    @products = Product.all
    if current_user
      @cart = Cart.new(user_id: current_user.id)
    end
    render 'index'
  end

  def new
    redirect_to root_path unless current_user
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(item_params)
      flash[:info] = "item updated"
      redirect_to item_path(@product)
    else
      flash[:info] = "Error updating item."
      redirect_to item_edit_path(@product)
    end
  end

  def create
    @product = Product.new(item_params)
    @product.user_id = current_user.id
    if @product.save
      if item_params[:image].present?
        @product.image.attach(item_params[:image])
      end
      flash[:info] = "Saved!"
      redirect_to root_path
    else
      flash[:alert] = "Error!"
    end
  end

  def item_params
    params.require(:product).permit(:id, :name, :description, :price, :amount, :image)
  end

end

app/views/products/index.haml
.row
  -# = render "partials/sidebar"
  .col-12
    %h4.my-4 Current Deals
    .card-columns
      - @products.each do |p|
        .card
          .image-wrap
            =image_tag(["tc-flashback", "strymon", "earthquaker", "vox"].sample, class: "item-image card-image-top")
          .card-body
            %h5.card-title
              = link_to(p.name, product_path(p.id))
            %p.card-text
              = p.description
            %h6.card-text.price
              $
              = p.price
            %p.card-text
              = p.amount
              left to complete this drop
            %p.card-text
              - if current_user
                = form_tag cart_path, method: :post do |c|
                  = hidden_field_tag(:product_id, p.id)
                  = submit_tag "Join Drop", class: "btn btn-success"
              - else
                = link_to "Join Drop", login_path, class: "btn btn-success join-drop"

app/views/products/new.haml
.row
  = render "partials/sidebar"
  .col-9
    %h5 New Item
    = form_for @product do |f|
      .form-group
        %label
          Name
        = f.text_field :name, class: "form-control"
      .form-group
        %label
          Price
        = f.text_field :price, class: "form-control"
      .form-group
        %label
          Amount
        = f.text_field :amount, class: "form-control"
      = f.submit "Submit", class: "btn btn-primary"

app/views/products/show.haml
.row
  .col-12
    .item.row.my-4
      .col-2
        =image_tag(["tc-flashback", "strymon", "earthquaker", "vox"].sample, class: "item-image card-image-top")
      .col-8
        %h5.item-title
          = @product.name
        %h6.price
          $
          = @product.price
        .stats
          = @product.amount
          left to complete this drop
        %p
          = @product.description
      .col-2
        - if current_user
          = form_tag @cart, action: cart_path, method: :post do |c|
            = hidden_field_tag(:product_id, @product.id)
            = c.submit "Join Drop", class: "btn btn-success"
        - else
          = link_to "Join Drop", login_path, class: "btn btn-success join-drop"